blank_issues_enabled: false
contact_links:
  - name: Ask a Question
    url: https://github.com//auanasgheps/snapraid-aio-script/discussions
    about: Please ask questions in our GitHub Discussions.
